//Try Cathc

const numero1 = 20;
const numero3 = 30;

console.log(numero1);

try {       //Va a intentar hacer algo y sino cae en el catch para poder leer el error             //Que reporte el error y luego siga su curso normal
    console.log(numero2)
}catch (error){
    console.log(error)
}

console.log(numero3);